### ISSUE TITLE
The slides for the ArchLinux talk from Feb 23 404

### ISSUE THREAD

**Issue by thenaterhood** [RITlug/ritlug.github.io#137]
http://ritlug.com/talks/2018/02/23/arch-linux.html - view slides, slides are missing. Probably a mistyped filename.

**Comment by Tjzabel** [comment]
@thenaterhood thank you for submitting an issue about this. I will ping @kst123abc about this issue.

**Comment by Tjzabel** [comment]
@thenaterhood website has been updated! Thank you for submitting this issue.
