### ISSUE TITLE
Projects section

### ISSUE THREAD

**Issue by ct-martin** [RITlug/ritlug.github.io#153]
We'd like a section highlighting projects/accomplishments of RITlug members. The new site (from #151) created the initial section, but it could use a little more work and a lot of content.

@icflournoy is currently working to contact alumni for projects they have worked on, including images & video where possible

I (@ct-martin) will be handling the technical implementation of this, including a minor bug with page summaries that exists in the current implementation.

If anyone has projects they'd like to include, please PM me or @icflournoy on Slack so we can make a page and reference the PR instead of filling up this issue (particularly if there are media files to transfer).

**Comment by Tjzabel** [comment]
@ct-martin with the new projects section of the website, how are you doing on this issue?

**Comment by ct-martin** [comment]
@Tjzabel I'm improving metadata stuff as I continue to add features. This issue is mainly on @icflournoy to get content

**Comment by Tjzabel** [comment]
I am going to mark this issue as closed, given that we have a projects section of the website.
