### ISSUE TITLE
Update Website Portion of Runbook

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/ritlug.github.io#154]
Since the RITlug website undertook a redesign, there are now some aspects of the Site Source that have undoubtedly changed. We should take this time to document what the new source code layout is.

**Comment by jwflory** [comment]
@Tjzabel I was a little confused at first, but I see now you mean the [Site Source](http://runbook.ritlug.com/en/latest/infrastructure/website.html#site-source) section of the Runbook. This is also an original page (i.e. 2014-2015) that I have not had a chance to rewrite. Admittedly, it probably needs a rehaul.

However, I think the better place to track this in the Runbook repo? Do you want to move this issue there?

**Comment by Tjzabel** [comment]
@jwflory yep! That's what I meant. Sorry for any confusion. After creating the other two issues I do believe it would be a good idea to move this issue to the runbook repo.
