### ISSUE TITLE
Re-introduce Announcements

### ISSUE THREAD

**Issue by jrtechs** [RITlug/ritlug.github.io#163]
We want to archive the current announcements section of the website and link to our campus groups announcements instead.

**Comment by ct-martin** [comment]
This issue is blocked on the mailing list forwarding working (see RITlug/tasks#21)

**Comment by ct-martin** [comment]
#165 partially completes this by removing the current announcements. Completion of this issue is still blocked on our announcements being forwarded to a public place.

**Comment by ct-martin** [comment]
Note from PR: there are some commented areas in the PR (for "deprecation" vs "removal" at this point) that will need to be cleaned up.

**Comment by ct-martin** [comment]
Reversed by RITlug/tasks#104
