### ISSUE TITLE
website runbook link in README 404s

### ISSUE THREAD

**Issue by deejoe** [RITlug/ritlug.github.io#168]
In

https://github.com/RITlug/ritlug.github.io/blob/master/README.md

is a link to

https://github.com/RITlug/runbook/blob/master/the-website.md

which seems no longer to exist in the current form of the runbook repo.

After a very cursory poking around, it's not immediately obvious to me what the link should be.

**Comment by jrtechs** [comment]
Nice catch Deejoe! That is supposed to link to the [RITlug runbook](http://runbook.ritlug.com/). I will update and fix that.
