### ISSUE TITLE
Add static page for Project Collaboration Meet-ups with dynamic date variable

### ISSUE THREAD

**Issue by jwflory** [RITlug/ritlug.github.io#171]
# Summary

Add static page for Project Collaboration Meet-ups (RITlug/tasks#39) with dynamic date variable for easier sharing / linking about our meet-ups

# Background

I was promoting another event at RIT and noticed the /r/RIT ["what's happening this week" thread](https://www.reddit.com/r/rit/comments/9nvbjp/whats_going_on_at_rit_and_rochester_oct_14_oct_20/). It would be cool to have a fixed web page explaining what our Project Collaboration Meet-ups are and when/where the next one will be held.

It also makes it easier to share a repeatable message for department newsletters, like the IST newsletter we feature in now.

# Details

The hard part already seems done up until now, with some of @ct-martin's recent PRs. I would imagine using a "blog post" for Project Collaboration Meet-ups, and then using a variable for the next planned date (stored with our other site-wide variables) for quickly and easily updating.

# Outcome

Easy to maintain web presence for Project Collaboration Meet-ups, easy to promote / share them with a fixed URL

---

_Related to #157._

**Comment by ct-martin** [comment]
This could be done in the "events" section, but I need to do a config thing so Jekyll will accept dates in the future. I would also suggest adding a section separate from events (or create subsections) to help differentiate regular meetings/meetups from ones that are major events such as Maker Faire and ImagineRIT. Another cool trick I _might_ be able to pull off is generating ICS calendar files people could add to their calendars.

**Comment by jwflory** [comment]
Importing recurring meetings to calendars would be cool. :+1:
