### ISSUE TITLE
Re-design the "about" and "getting involved" pages

### ISSUE THREAD

**Issue by ct-martin** [RITlug/ritlug.github.io#175]
* Formally merge `/about` & `/get-involved`, or split the content to make proper pages for both
* Make prettier, like done for the home & TigerOS pages
* Depending on RITlug/tasks#84, ability to add affiliate/sponsor links
* New template with quick details sidebar that contains meeting time/place and other info?

**Comment by ct-martin** [comment]
@RITlug/eboard-2018-2019 other than the sponsor thing (we can discuss site specifics post- RITlug/tasks#84), thoughts?

**Comment by Tjzabel** [comment]
@ct-martin this issue was closed from your mention lol. Don't use the words "close" and "issue #" next to each other, or else it closes the issue ^.^

**Comment by Tjzabel** [comment]
## Additional Details
In order for the About and Homepage pages to be officially declared "redesigned," the sponsor images need to be in line with one another. Attaching images of the issue.

### Homepage
![new_website_affiliates](https://user-images.githubusercontent.com/22552344/48662376-55f16700-ea4f-11e8-8d74-f59d5cef513a.png)

### About page
![website_about_affiliates](https://user-images.githubusercontent.com/22552344/48662382-5c7fde80-ea4f-11e8-8f4d-79eefb473f94.png)

**Comment by ct-martin** [comment]
Stickermule's logo has an extra margin around it and states that we're not
allowed to crop it

--
Christian Martin (Phone)

**Comment by Tjzabel** [comment]
@ct-martin all the same, still something we'll need to do in the future.

**Comment by ct-martin** [comment]
From long-term planning:

* Put call-outs to committees (Events & Projects) on the Getting Involved page
  * inc. info on giving a talk or starting a project
  * Example: [About page's call-out for Getting Involved](https://ritlug.com/about/)
* Clean up the multiple lists of links to something cleaner on Getting Involved
  * Similar to home page's links?
* About should be more focused on the text of what RITlug is/does/is involved with, Getting Involved can have a TL;DR but should focus on the actual ways to get involved

**Comment by jrtechs** [comment]
Closed in #185. We can re-address this with a new issue when we have new/more specific things we want to add to the website.
