### ISSUE TITLE
Site title doesn't use {{ site.title }}

### ISSUE THREAD

**Issue by thenaterhood** [RITlug/ritlug.github.io#24]
The current templates don't make use of {{ site.title }} (in _includes/head.html), they have RITlug hardcoded and probably shouldn't. Minor issue, but it makes forking the site for other purposes easier.

**Comment by patkub** [comment]
@thenaterhood does this issue still exist?

**Comment by thenaterhood** [comment]
Yes.
Here: https://github.com/RITlug/ritlug.github.io/blob/master/_includes/head.html#L25
and possibly here: https://github.com/RITlug/ritlug.github.io/blob/master/_includes/header.html#L6

I'm not sure how much value this provides overall, but it makes it easier to get up and running if you fork the site.

**Comment by Serubin** [comment]
Merged and fixed
