### ISSUE TITLE
Post Linux Gaming Slides

### ISSUE THREAD

**Issue by jrtechs** [RITlug/ritlug.github.io#243]
Post the slide deck for the Linux gaming talk on the website.

**Comment by Tjzabel** [comment]
@jrtechs @hkeena98 so the gaming on Linux stuff have been updated on the website.

It's the actual slides and stuff that we're missing. However, @jrtechs we don't usually post the slides themselves for the website when it's a RITlug member doing the rpesentation.

We can start doing that going forward though, if you feel that should be something we do.

**Comment by jrtechs** [comment]
I feel that posting as many slides as possible is better since it gives members more resources to look at. 

I still don't see the slides on the live website @Tjzabel 

This is weird since the files have been uploaded and we've had a build go through. 
https://github.com/RITlug/ritlug.github.io/blob/master/talks/_posts/2019-w10-gaming-on-linux.md
https://github.com/RITlug/ritlug.github.io/blob/master/talks/slides/2019-w10-gaming-on-linux.pdf

![last](https://user-images.githubusercontent.com/13894625/68422223-c2d4a400-016d-11ea-9a48-7d65e96b72f4.PNG)

**Comment by Tjzabel** [comment]
Showing up correctly here: https://ritlug.com/talks/2019/11/01/gaming-on-linux/

**Comment by jrtechs** [comment]
Spooky, I guess sending out the email triggered a rebuild

**Comment by Tjzabel** [comment]
@jrtechs nope. I put up a PR to solve the issue. It was a file naming issue.

**Comment by jrtechs** [comment]
ah, thanks!
