### ISSUE TITLE
Remove Stickermule sponsorship from website

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/ritlug.github.io#263]
## Why
Stickermule is no longer sponsoring RITlug, and we need to reflect this status.

**Comment by jrtechs** [comment]
Hey, guys, I'm gonna work on this issue in the next day or two. I'm just going to remove the sticker mule from the affiliates section and make OSSN and FOSS@MAGIC 50% of the width. 

![Screenshot_2020-03-01_17-09-20](https://user-images.githubusercontent.com/13894625/75634839-18cacd00-5bdf-11ea-9ee3-345b51388775.png)
