### ISSUE TITLE
Add links to post feeds

### ISSUE THREAD

**Issue by thenaterhood** [RITlug/ritlug.github.io#28]
RITlug's website currently provides a feed for current announcements and hopefully in the future, a feed for talks (see #27). There aren't any site links for finding those feeds.

**Comment by axk4545** [comment]
@thenaterhood is this still an issue? I can't tell if [#27](https://github.com/RITlug/ritlug.github.io/issues/27) solved it.

**Comment by thenaterhood** [comment]
No. 27 added the feeds themselves, but there's no links to them anywhere on the site.

**Comment by patkub** [comment]
@thenaterhood @axk4545 the navigation bar has links to announcements and talks. Is this resolved?

**Comment by thenaterhood** [comment]
I think what I had in mind was having links to the RSS/ATOM (w/e format they are) feeds should someone want to subscribe that way.

**Comment by patkub** [comment]
Oh I see. We have the xml files, just no links to them. http://ritlug.com/feeds/latest.xml (announcements) and http://ritlug.com/feeds/talks.xml

**Comment by patkub** [comment]
Added feed links to the footer in PR https://github.com/RITlug/ritlug.github.io/pull/95.

**Comment by jflory7** [comment]
@patkub Woot woot! Thanks for your help on clearing this one out. 💃
