### ISSUE TITLE
Needs updated for Fall 2015

### ISSUE THREAD

**Issue by deejoe** [RITlug/ritlug.github.io#3]
According to word on the street and to https://thelink.rit.edu/organization/Linux RITlug is in fact meeting during the Fall 2015 semester.  However, stuff on this web site is left over from fall 2014 and spring 2015

**Comment by thenaterhood** [comment]
We're aware. We're working on a complete rebuild of the site this semester and we'll be pushing up a load of updates once that's complete. Until then, the site won't see much activity.

RITlug meets every Friday 4-6PM during the academic year as we have for the past couple of years.

**Comment by deejoe** [comment]
Maybe a post to the google group to that effect would be in order, so that
at least some of the non-RIT-hosted presence for the group indicates signs
of life?

I'm teaching the HFOSS course but until finding the reference at The Link
(mostly by happenstance, I was looking at the recruiting diversity thing for
the career day tomorrow) I had no public URL to pass along to facilitate
their participation.


Thanks for the update, all the same, and good luck with the rebuild.

-- 
Joe



On Tue, Sep 29, 2015 at 12:15:37PM -0700, Nate Levesque wrote:
> We're aware. We're working on a complete rebuild of the site this semester and
> we'll be pushing up a load of updates once that's complete. Until then, the
> site won't see much activity.
> 
> RITlug meets every Friday 4-6PM during the academic year as we have for the
> past couple of years.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
-- 
Joe   On ceding power to tech companies: http://xkcd.com/1118/
man screen | grep -A2 weird
  A weird imagination is most useful to gain full advantage of
  all the features.

**Comment by thenaterhood** [comment]
Thanks! We're working on improving our processes so we can avoid running into issues like this.

Closing, since #4 will be completed soon and will get everything back up and running.
